### ISSUE TITLE
Streaming Response

### ISSUE THREAD

**Issue by leifg** [elixir-tesla/tesla#271]
According to the README, Tesla supports streaming if the underlying adapter supports it.

From the code and the examples I found it seems though that streaming means in this instance, streaming of the request.

I am interested in how I would be able to stream the response of a request (very useful for something like large downloads).

Is this supported, if so: how?

**Comment by teamon** [comment]
Unfortunately streaming response body is not implemented, but it could be done. 
I can imagine something like:

```ex
case Tesla.get(client, "/stream", stream_response: true) do
  {:ok, env} -> # on successful read of status & headers env.body is a Stream
  {:error, reason} -> # ...
end
```

**Comment by teamon** [comment]
I'd go with `Tesla.get(client, "/path", response: :stream)` (instead of `stream_response: true`)

**Comment by teamon** [comment]
Response streaming added for Finch in https://github.com/elixir-tesla/tesla/releases/tag/v1.9.0
