### ISSUE TITLE
Make runtime middleware more prominent in docs

### ISSUE THREAD

**Issue by wojtekmach** [elixir-tesla/tesla#377]
First of all, thank you for this library. And apologies if something like this was already discussed, I couldn't easily find it.

In the very first example in README we have:

```elixir
defmodule GitHub do
  use Tesla

  plug Tesla.Middleware.BaseUrl, "https://api.github.com"
  plug Tesla.Middleware.Headers, [{"authorization", "token xyz"}]
  plug Tesla.Middleware.JSON

  def user_repos(login) do
    get("/users/" <> login <> "/repos")
  end
end
```

and we bake in `token xyz` which is almost never a good idea. But the main problem is we've then  seen folks following the pattern from README and ending up with:

```elixir
  plug Tesla.Middleware.Headers, [{"authorization", "token #{Application.fetch_env!(:myapp, :token)}"}]
```

which is the whole compile-time vs runtime configuration situation and a common source of bugs and confusion.

There's already an excellent section on [Runtime Middleware](https://hexdocs.pm/tesla/readme.html#runtime-middleware) and my proposal would be to make that more prominent, basically consider that as the default way of doing things, and slowly move off of macro-based approach.

My only suggestion is perhaps this would be more approachable as a very first example:

```elixir
defmodule GitHub do
  def user_repos(login) do
    Tesla.get(client(), "/user/" <> login <> "/repos")
  end

  defp client() do
    token = "xyz"

    Tesla.client([
      {Tesla.Middleware.BaseUrl, "https://api.github.com"},
      Tesla.Middleware.JSON,
      {Tesla.Middleware.Headers, [{"authorization", "token: " <> token }]}
    ])
  end
end
```

that is, we have exactly same usage of `GitHub.user_repos("teamon")` as in the existing docs. But I think the current "runtime middleware" example with passing the client around in calling code is an important one too.

**Comment by teamon** [comment]
I agree 100% 🙃 

There are few reasons why I stalled with README change:

1. Non-macro clients are a bit more complex to start with and less familiar to the ones who know plug. Nowadays most of the clients I write look like this:
      ```elixir
        def new do
          config = Application.get_env(:myapp, __MODULE__, [])

          middleware = [
            Tesla.Middleware.Telemetry,
            Tesla.Middleware.JSON,
            Tesla.Middleware.Logger,
            ... # use config here
          ]

          adapter = config[:adapter] || Tesla.Adapter.SomeDefault

          Tesla.client(middleware, adapter)
        end
      ```
    Which might be a bit too much to start with. On the other hand, removing the `Application.get_env/3` call makes one wonder why this code can't be defined as `@middleware`.

2. Changing README might cause confusion for people landing on README while reading macro-based code. 
The first example would look nothing like their code which is quite a bad experience.

I guess it goes down to the question what causes more confusion: the current state with compile-time vs runtime config or changing the README.

**Comment by wojtekmach** [comment]
I'm worried that in effort to make things accessible we're nudging people in the wrong direction, the current top of the readme looks perhaps familiar but it's arguably wrong. Almost everyone needs to have some kind of auth token so I think showing how to correctly grab it is really important.

Regarding 2., we have top of readme (macros) and runtime middleware section; I'd reverse them, top of readme would talk about runtime middleware and some latter section about macros. And perhaps top of the readme will briefly mention `use Tesla` and point to the rest of the docs.

This is a separate discussion, but backwards-compatibility aside for a second, do you see macro-based API used by folks long term? I personally don't, the auth and similar things are a total deal breaker for me. (Not to mention it makes implementation more complicated.) So if the plan would be to ever move off of them, you need to start somewhere. :)

**Comment by teamon** [comment]
It's... complicated. Most of the time I use runtime middleware only as there are is always something you want to configure in runtime (auth, timeout, url, fuse params, etc.) At the same time, I've written a bunch of macro-based clients for internal microservices where e.g. auth was not necessary.

I personally despise breaking changes, but _hiding_ end user macros and promote dynamic middleware has been on my mind for (years 🙈 ) now.

If we ever get to tesla 2.0 I'd probably drop macros, as the migration is not that hard.

**Comment by wojtekmach** [comment]
just to be clear, I wasn't proposing to drop macro-based api anytime soon, rather to: first, make it an exception not the rule; then, let it slowly fall into oblivion :) (and in a few years you can drop it or keep it, it doesn't really matter!)

**Comment by yordis** [comment]
Docs have been updated; people are directed to use `Tesla.client/2` instead of macro usage.
