### ISSUE TITLE
Finch does not format headers

### ISSUE THREAD

**Issue by kanes115** [elixir-tesla/tesla#495]
It might come from misunderstanding of adapters but I don't see a reason why Finch should not format headers in the same way that Hackney does [here](https://github.com/teamon/tesla/blob/master/lib/tesla/adapter/hackney.ex#L38). This impedes the ability to use middleware like JSON (which checks `content-type` header but not `Content-Type`).

**Comment by Yarnus** [comment]
eh...Hey @teamon I'm just trying to figure it out. 

From my understanding,  `Finch` is built on top of [`Mint`](https://github.com/elixir-mint/mint)

Therefore I found `Mint` has realted handling:
- [HTTP1](https://github.com/elixir-mint/mint/blob/1ea7731d921840ad75a47fa9415525c3d94b9980/lib/mint/http1.ex?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L239)
- [HTTP2](https://github.com/elixir-mint/mint/blob/1ea7731d921840ad75a47fa9415525c3d94b9980/lib/mint/http2.ex?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L486)

Do we need to do it again at the `Tesla.Adapter.Finch` 🤔 

(hope I understood your point.

**Comment by teamon** [comment]
@kanes115 Could you provide an example?

I did a quick check and everything seems to be just fine:

CamelCase (original) headers with curl

```
> curl -i http://google.com
HTTP/1.1 301 Moved Permanently
Location: http://www.google.com/
Content-Type: text/html; charset=UTF-8
Date: Fri, 17 Dec 2021 14:15:53 GMT
Expires: Sun, 16 Jan 2022 14:15:53 GMT
Cache-Control: public, max-age=2592000
Server: gws
Content-Length: 219
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
```

lowercase headers with Finch:

```
iex(1)> Finch.start_link(name: :a)
iex(2)> Finch.build(:get, "http://google.com", [], nil) |> Finch.request(:a)
{:ok,
 %Finch.Response{
   body: "...",
   headers: [
     {"location", "http://www.google.com/"},
     {"content-type", "text/html; charset=UTF-8"},
     {"date", "Fri, 17 Dec 2021 14:14:09 GMT"},
     {"expires", "Sun, 16 Jan 2022 14:14:09 GMT"},
     {"cache-control", "public, max-age=2592000"},
     {"server", "gws"},
     {"content-length", "219"},
     {"x-xss-protection", "0"},
     {"x-frame-options", "SAMEORIGIN"}
   ],
   status: 301
 }}
```
