### ISSUE TITLE
Mint passive mode

### ISSUE THREAD

**Issue by teamon** [elixir-tesla/tesla#509]
## tl;dr

Switch `Tesla.Adapter.Mint` to use passive mode, as suggesting in https://github.com/teamon/tesla/issues/357#issuecomment-916967770

## (Potentially) related issues:
- https://github.com/teamon/tesla/issues/357
- https://github.com/teamon/tesla/issues/450
- https://github.com/teamon/tesla/issues/394
- https://github.com/teamon/tesla/issues/385
- https://github.com/teamon/tesla/issues/370

**Comment by fbergero** [comment]
@teamon I'd like to tackle this one

**Comment by fbergero** [comment]
@teamon We basically want to change the default `active` mode to `passive`  here https://github.com/elixir-tesla/tesla/blob/master/lib/tesla/adapter/mint.ex#L51 right?

**Comment by teamon** [comment]
Basically yes :) 

In case of tests it would be great to have failing test cases for all related issues and then check if changing to passive mode fixes them.
