### ISSUE TITLE
Tesla mix lock for {:finch, "~> 0.3", optional: true} many version behind

### ISSUE THREAD

**Issue by dantuck** [elixir-tesla/tesla#544]
### Discussed in https://github.com/elixir-tesla/tesla/discussions/543

<div type='discussions-op-text'>

<sup>Originally posted by **dantuck** September 14, 2022</sup>
I am seeing that the current release of Tesla has the finch dep set to `{:finch, "~> 0.3", optional: true}` when the latest release of finch is at `0.13.0`.

We are wondering if it is safe to override to `0.13.0` -> `{:finch, "~> 0.13.0", override: true}`?

Thanks for any input!</div>

**Comment by teamon** [comment]
@dantuck The best way would be to just try it, and when you do please let us know if everything works fine 🙏

**Comment by dantuck** [comment]
Thanks @teamon. We will very likely give this a go and if it works ill get a PR in.

**Comment by dantuck** [comment]
@teamon [PR](https://github.com/elixir-tesla/tesla/pull/547) created and ready for review.

**Comment by yordis** [comment]
@dantuck ✅
