### ISSUE TITLE
Does Tesla add a "TE" header to the request?

### ISSUE THREAD

**Issue by travelmassive** [elixir-tesla/tesla#551]
Tesla appears to add a "TE" header to the request even when I specify empty headers. This can be problematic when trying to perform a request where exact headers are required.

Here's a quick example request to https://www.whatismybrowser.com which reports the headers requested.

```
{:ok, result} = Tesla.get(
  "https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending",
  headers: []
)
IO.inspect(result.body, printable_limit: :infinity) # may need to adjust depending on your IEX settings
```

Examine the output (formatted for readability below), and there's a "TE" header 

```
There were 5 headers sent:
          
CONNECTION
keep-alive
              
CONTENT-LENGTH
0

CONTENT-TYPE

HOST
www.whatismybrowser.com

TE
```

Is there a way to remove the "TE" header?

**Comment by travelmassive** [comment]
Thanks for the tip. I tried switching between Mint and Httpc adapters and still get a "TE" header.

I also double checked by making a request to my own web server and printing the headers received on the server, and still get the "TE" header.

Below is a quick module that I run in IEX:

```defmodule WhatHeadersAmISending do

  # Using 1.4.4
  use Tesla

  adapter Tesla.Adapter.Mint
  #adapter Tesla.Adapter.Httpc

  def run do
    {:ok, result} = Tesla.get("https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending", headers: [{"ExampleHeader", "elixir"}])
    # the headers reported on the web page are in a <table> so just find and print the table cells
    # see: view-source:https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending
    Regex.scan(~r/t[h|d]>.*?<\/t[h|d]/, result.body)
  end
end
```

I'm not really sure where to look to solve this. It's not critical for me but now I'm curious where the header is coming from!

**Comment by yordis** [comment]
Since it is a `httpc` as far as I can tell. Should we close this issue?
