### ISSUE TITLE
Authenticity is not established by certificate path validation

### ISSUE THREAD

**Issue by Leastrio** [elixir-tesla/tesla#554]
Getting this error with my application
```elixir
[warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'
```

Is this important to look at? Im just making a few get requests to a private api.

**Comment by yordis** [comment]
It is a warning, it is not required but definitely encouraged to make sure you are setting up certificates correctly, `more secure`.

Are you sure it is Tesla?
What adapter are you using?
Could you use `Mint` since it comes with good security practices by default?

**Comment by Leastrio** [comment]
Switching to mint fixed the error
