### ISSUE TITLE
[Bug] Unable to install Tesla due to castore minimum dependency version 0.1

### ISSUE THREAD

**Issue by liamstevens111** [elixir-tesla/tesla#559]
Running `mix deps.get` with version `1.4 or 1.5` of Tesla, the following error is shown:

```elixir
Because "the lock" specifies castore 1.0.0 and tesla >= 1.3.0 depends on castore ~> 0.1, the lock is incompatible with tesla >= 1.3.0.
And because your app depends on the lock, tesla >= 1.3.0 is forbidden.
So, because your app depends on tesla ~> 1.5, version solving failed.
```

This is because `castore` upgraded to 1.0.0 last month and Phoenix automatically upgrades castore on new projects to 1.0.0 in the lock file from their dependency:
```
# TODO drop castore when we require OTP 25+
{:castore, ">= 0.0.0"},
```

I see this repo has a PR merged here that `seems` would fix it - https://github.com/elixir-tesla/tesla/pull/556

Do we know when this will be released? Or is is there another workaround?

Thanks.

**Comment by yordis** [comment]
I released `v1.5.1`
