### ISSUE TITLE
Retry middleware: Is there a way to know which request is being retried?

### ISSUE THREAD

**Issue by egeersoz** [elixir-tesla/tesla#578]
I know we can do this:
```
should_retry: fn
  {:ok, %{status: status}} when status in [400, 500] -> true
  {:ok, _} -> false
  {:error, _} -> true
end
```
I'm running into some timeout issues, which from what I can tell emit `{:error, :timeout}`. The retry logic in that function clause (the third one) work fine, but I also want to log the occurrence in the console in the form of:

```
The request to #{url} timed out after #{timeout_seconds}. This will be the #{retry_count} time the request is being retried.
```

Is there a way to add this type of detailed logging?

Use case: I have an importer that imports a whole bunch of data from various APIs, and the total number of possible URLs that data might be fetched from is in the hundreds. I need to know exactly which endpoints are timing out, and how frequently, so I can troubleshoot on the other end.

**Comment by yordis** [comment]
There is no way to accomplish that as of today:

https://github.com/elixir-tesla/tesla/blob/30c3a298bc0de841d8929055429598342ef75573/lib/tesla/middleware/retry.ex#LL90C16-L90C28

Open to accepting a function with two arities passing an object with extra information.
