### ISSUE TITLE
Cryptic {:error, :closed} return from a POST

### ISSUE THREAD

**Issue by kybishop** [elixir-tesla/tesla#597]
Hey all,

We're using the Hackney adapter and latest version of Tesla. We're occasionally seeing a `{:error, :closed}` error when `POST`ing and can't find any info about this. The only reference to `:closed` is in the test for the mint adapter.

1. What does this error mean? Is it the remote closing of a TCP connection?
2. What recourse do we have when this happens? Tesla states that it will already retry in most cases, but does this bubbling up imply that all retries failed?
3. Some documentation on this would be amazing; happy to put in a PR myself if we can get info on triggers and solutions.

Thank you!
Ky

**Comment by yordis** [comment]
> What does this error mean? Is it the remote closing of a TCP connection?

I am not sure but I would suggest using another adapter. I found some opened issues related to the topic https://github.com/benoitc/hackney/issues/439 https://github.com/benoitc/hackney/issues/630

> What recourse do we have when this happens? Tesla states that it will already retry in most cases, but does this bubbling up imply that all retries failed?

You need to add `Tesla.Middleware.Retry` middleware, check `Tesla.Middleware.Retry` documentation to learn more about it.

> Some documentation on this would be amazing; happy to put in a PR myself if we can get info on triggers and solutions.

Improvements are always welcome 💜

**Comment by yordis** [comment]
Feel free to create a PR with your suggested changes

**Comment by kybishop** [comment]
For anyone else who stumbles upon this issue, adding a simple retry (as suggested by yordis) has eliminated this issue for us.

`{Tesla.Middleware.Retry, delay: 1000, max_retries: 5}`
