### ISSUE TITLE
Mint proxy credentials

### ISSUE THREAD

**Issue by klevison** [elixir-tesla/tesla#610]
How can I set proxy credentials when using `Tesla.Adapter.Mint`  . According `https://hexdocs.pm/tesla/Tesla.Adapter.Mint.html` It should be something like `{:http, "127.0.0.1", 8888, []} `, but where can I pass credentials just like: `{Tesla.Adapter.Hackney, [proxy: {"1.2.3.4", 1234}, proxy_auth: {"user", "pass"}]}` ?

**Comment by yordis** [comment]
There are multiple ways you could configure it.

Please read https://hexdocs.pm/tesla/Tesla.Adapter.Mint.html and https://hexdocs.pm/tesla/Tesla.html#client/2
