### ISSUE TITLE
Issues Working with QuotaGuard QGTunnel

### ISSUE THREAD

**Issue by qgtim** [elixir-tesla/tesla#611]
Running Tesla while running QuotaGuard's QGTunnel software in transparent mode causes Tesla to no longer work.  The transparent mode for quotaguard uses a .so file that will override DNS lookup for records that are configured in the tunnel configuration.  

For some reason, when enabling transparent mode, it will make Tesla not work all together.  The scenario we saw this in most recently was when we were using Ecto to connect through QGTunnel.

Steps to reproduce:
1. Download the QGTunnel software into the root of your project
```
curl https://s3.amazonaws.com/quotaguard/qgtunnel-latest.tar.gz | tar xz
```
The SO file in question will be available at `vendor/nss_wrapper/libnss_wrapper.so`

2. Create `.qgtunnel` file that enables transparent mode
```
[qgtunnel.example]
accept = "localhost:5432"
connect = "tcp://quotaguard.com:5432"
transparent = true
```

3. Run your application with the qgtunnel
```
QUOTAGUARDSTATIC_URL=http://user:pass@proxy.quotaguard.com:9293 ./bin/qgtunnel mix run
```

Note: the above instructions do not require a quotaguard account to reproduce the problem.

Behavior: Tesla requests fail.

The QGTunnel .so file should only be overriding quotaguard.com DNS requests to return 127.0.0.1.  This QGTunnel software is used acrossed a lot of applications, languages, and TCP protocols.  We have never seen this type of behavior before until we encountered running the QGTunnel beside the Tesla client.

The solution we have utilized so far is to disable transparent mode, which disables the use of DNS override and the use of the .so file.  Any help understanding why this is only an issue when utilizing Tesla would be very much appreciated.

**Comment by yordis** [comment]
What adapter are you using?

Tesla barely does anything at the HTTP client level except mapping some data structures in and out. So, my gut feeling is telling me that Tesla isn't the issue here, especially if you ran into the same issue with Ecto (unless I misunderstood).

**Comment by qgtim** [comment]
What I am saying is that Ecto is setup to go through the QGTunnel (by using 127.0.0.1:5432) and Tesla is not configured to use any proxy or utilize the QGTunnel.

Here is an example that shows it "working" when transparent mode is disabled: https://github.com/quotaguard/shield-examples/tree/fix-tesla-issue/elixir/https/tesla

In this example we aren't even using the QGTunnel, just starting it up.

If you run `docker build -t qg-shield-elixir-https-tesla-example .` and then `docker run -e QUOTAGUARDSHIELD_URL=https://fake:pass@proxy.quotaguard.com:9294 qg-shield-elixir-https-tesla-example` it will give you an output with the IP address of the requester.

If you then change the `.qgtunnel` file to have `transparent = true`, then `docker build -t qg-shield-elixir-https-tesla-example .` and then `docker run -e QUOTAGUARDSHIELD_URL=https://fake:pass@proxy.quotaguard.com:9294 qg-shield-elixir-https-tesla-example`, you will get:
```
** (MatchError) no match of right hand side value: {:error, :econnrefused}
    (qg 0.1.0) lib/qg.ex:14: Qg.request_ip/0
    nofile:1: (file)
    (stdlib 5.0.2) erl_eval.erl:750: :erl_eval.do_apply/7
    (elixir 1.15.4) lib/code.ex:543: Code.validated_eval_string/3
    (elixir 1.15.4) lib/enum.ex:984: Enum."-each/2-lists^foreach/1-0-"/2
```

**Comment by yordis** [comment]
`{:error, :econnrefused}` that comes from `gen_tcp` when using `httpc`, nothing related to Tesla.

I switched to `Mint` and I got:

```
no match of right hand side value: {:error, %Mint.TransportError{reason: :nxdomain}}
```


I am sorry but I am not familiar with that tool, and I can not help you much here.
