### ISSUE TITLE
[Proposal] Lower the usage of macros

### ISSUE THREAD

**Issue by yordis** [elixir-tesla/tesla#612]
> https://github.com/elixir-tesla/tesla/issues/367#issuecomment-610342739
> I would discourage usage of macros for DRY. It's better to use the [Runtime middleware](https://github.com/teamon/tesla#runtime-middleware).

After many years of using Tesla, I came across too many situations that are much simpler to deal with using the Runtime middleware, slowing questioning the value of having macros.

@teamon I am not sure if you still feel strongly about having such a feature or if it would be something that maybe is worth deprecating/discouraging/removing in the future.

**Comment by yordis** [comment]
https://github.com/elixir-tesla/tesla/pull/575/files is an example where the macro style ends up wanting a Runtime Middleware style of execution (not quite, but similar)

So eventually, every middleware will end up having to support `MFA,` static values, and function pointers ... it is just a matter of somebody wanting to do it their style.

Versus Runtime Middleware removing all that complexity.

**Comment by teamon** [comment]
[🎶 Hello macros my old friend 🎶 ](https://github.com/elixir-tesla/tesla/issues/377)

The first step would be to update the README and make the runtime middleware the default way, while keeping macros for backwards compatibility.

**Comment by yordis** [comment]
Docs updated for now, v2 we **may** remove the macro all together
