### ISSUE TITLE
Logger debug: true does nothing at runtime

### ISSUE THREAD

**Issue by tfwright** [elixir-tesla/tesla#671]
Docs for Logger middleware say: 

> In order to be able to set :debug at runtime we can pass it as a option to the middleware at runtime.

So I expected to be able to toggle response logging on at off when configuring clients at runtime by configuring it like so: `{Tesla.Middleware.Logger, debug: true}`

 But this does not appear to change logger behavior.

Since the docs also say something about the value of Logger level at compile time, I suspect what I am trying to do may not be possible currently? But it seems like it should be. My use case is that I don't normally want to log responses in prod, but sometimes I'd like to troubleshoot an issue by consoling in to that env.

**Comment by teamon** [comment]
Using `{Tesla.Middleware.Logger, debug: true}` will call `Logger.debug`, but it will only show if your logger level is set to `:debug` (You can use `Logger.configure(level: :debug)` in console to change it)

**Comment by tfwright** [comment]
It looks like the issue was I had some incorrectly formatted headers that seemed to work for dispatching the actual request but were breaking logging: `cannot truncate chardata because it contains something that is not valid chardata`. When I changed the header keys from atoms to strings request logs started appearing again. 

If that is indeed the issue, what do you think about prefacing that error message with something like "error rendering logs: " to make it a bit more clear that debug line is _in place_ of where logs would have been emitted if not for the given error.

**Comment by yordis** [comment]
I updated the docs, please feel free to send a PR suggesting some changes
