### ISSUE TITLE
Compiler warnings with Elixir v1.17.0-rc.0

### ISSUE THREAD

**Issue by nathany-copia** [elixir-tesla/tesla#676]
```
Compiling 38 files (.ex)
    warning: single-quoted strings represent charlists. Use ~c"" if you indeed want a charlist or use "" instead
    │
 75 │       handle(:hackney.request(method, url, headers, body || '', opts), opts)
    │                                                             ~
    │
    └─ lib/tesla/adapter/hackney.ex:75:61
```

**Comment by yordis** [comment]
PR welcome, but before we could even upgrade Elixir, we need to fix the CI for https://github.com/elixir-tesla/tesla/pull/623

It is related to SSL certs and testing dept. I would appreciate your support with it.

**Comment by AndrewDryga** [comment]
@yordis the warning was fixed in `main`, I think all we have left to close this one is to publish a new version to Hex.pm.

**Comment by yordis** [comment]
Released 🚀 💜
