### ISSUE TITLE
Adapter specific options not passed to Finch

### ISSUE THREAD

**Issue by visciang** [elixir-tesla/tesla#714]
Version: 1.12.1

App configuration:

```elixir
config :tesla, :adapter, {Tesla.Adapter.Finch, name: XXX.Finch}
```

Adapter module:

```elixir
defmodule XXX.Finch do
  use Tesla

  adapter Tesla.Adapter.Finch, name: __MODULE__, receive_timeout: 40_000
end
```

Expected:

Finch request (`Tesla.Adapter.Finch.request`) should be called with `[receive_timeout: 40_000, name: XXX.Finch]`.
Actually it is called with the default options `[receive_timeout: 15_000, name: XXX.Finch]`.

**Comment by yordis** [comment]
Hey there, I could not reproduce this

```elixir
config :tesla, :adapter, {Tesla.Adapter.Finch, name: XXX.Finch}

defmodule XXX.Finch do
  use Tesla

  adapter Tesla.Adapter.Finch, name: __MODULE__, receive_timeout: 40_000
end
```

```elixir
XXX.Finch.get("http://...")
```

Please provide some test case proving the brokenness, a video or something that I could replicate this with
